### PR TITLE
Upstream release v1.2.0-rcgit-28

### PR DESCRIPTION
**Pull request by antenore**
This should be fine for the release, let me know.
Thanks for your support!

### CODE REVIEW

**Review by amtlib-dot-dll — APPROVED** [review]

**Comment by amtlib-dot-dll** [comment]
BTW, do you noticed this https://github.com/flathub/flathub/pull/307#pullrequestreview-104844739? These lines are still there @antenore :thinking:

**Review by amtlib-dot-dll — CHANGES_REQUESTED** [review]
https://github.com/flathub/flathub/pull/307#pullrequestreview-104844739

**Review by amtlib-dot-dll — APPROVED** [review]
Well I didn't read the issue. So it's ok.

**Comment by amtlib-dot-dll** [comment]
Well now that you have push access you don't need to open a pull request here :grinning: I am neither a Flathub member nor a Remmina maintainer.

**Comment by antenore** [comment]
Thanks. We cannot accept those requests and it's not a bug. I hope they will accept it.

Do you want to join the Remmina team? This way you can work directly on the original file.

**Comment by amtlib-dot-dll** [comment]
That would be a great idea :grinning: thanks

**Comment by antenore** [comment]
@amtlib-dot-dll we have just released the rcgit-29 can you kindly do what is needed to update the flatpak? 
Me and @giox069 have fixed everything is important and we should not touch Remmina for some weeks at least. I really hope this time we will see Remmina on flathub.

**Comment by antenore** [comment]
for reference https://github.com/FreeRDP/Remmina/releases/tag/v1.2.0-rcgit.29

**Comment by amtlib-dot-dll** [comment]
Thank you very much! I will change the recipe here https://github.com/FreeRDP/Remmina/blob/next/flatpak/org.remmina.Remmina.json correspondingly after accepted by Flathub

https://github.com/flathub/flathub/pull/307#issuecomment-379607358

**Comment by antenore** [comment]
Yes, keep @larchunix in the loop when you will do.
Thank you

**Pull request merged**
